[tool.poetry]
name = "gst-audit"
version = "0.0.1"
description = "Audit tool for GStreamer"
authors = ["Fluendo S.A. <support@fluendo.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
frida = "*"
fastapi = "*"
fastapi-sse = "*"
colorlog = "^6.8.2"
